package com.hollandsmp.staffsessionapi.model;

public enum FailureReason {
    STAFFER_ALREADY_IN_SESSION,
    TARGET_ALREADY_INVESTIGATED,
    PERMISSION_DENIED,
    SESSION_UNAVAILABLE,
    INVALID_TARGET,
    INVALID_AREA,
    TIER_RESOLUTION_FAILED,
    TRANSACTION_ACTIVE,
    CORRUPTED_SESSION,
    INVALID_STATE,
    INVALID_INVESTIGATION_TYPE,
    NO_ACTIVE_SESSION,
    DATABASE_ERROR,
    ERROR
}
